name: vendorizor
description: No moar symlinkz!
version: 0.0.1
author: Seth Ladd <sethladd@gmail.com>
homepage: TBD

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  package_config: any
  path: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'

executables:
  vendorizor:
